import React, { useState } from 'react';
import { 
  X, 
  ShieldAlert, 
  Ban, 
  ShieldCheck, 
  Terminal, 
  Copy, 
  Check, 
  Clock, 
  User, 
  AlertTriangle, 
  AlertCircle, 
  FileText, 
  Download, 
  Share2,
  ArrowLeft
} from 'lucide-react';
import { LogEntry, SuspiciousIP, RiskLevel } from '../types';

interface IPDetailsModalProps {
  ip: string;
  suspiciousData?: SuspiciousIP;
  entries: LogEntry[];
  onClose: () => void;
  onToggleBlock: (ip: string) => void;
  onToggleWhitelist: (ip: string) => void;
  isBlocked: boolean;
  isWhitelisted: boolean;
}

export const IPDetailsModal: React.FC<IPDetailsModalProps> = ({
  ip,
  suspiciousData,
  entries,
  onClose,
  onToggleBlock,
  onToggleWhitelist,
  isBlocked,
  isWhitelisted
}) => {
  const [copiedIptables, setCopiedIptables] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);
  const ipLogs = entries.filter(e => e.ip === ip);

  const iptablesCommand = `iptables -A INPUT -s ${ip} -j DROP`;

  const handleCopyIptables = () => {
    navigator.clipboard.writeText(iptablesCommand);
    setCopiedIptables(true);
    setTimeout(() => setCopiedIptables(false), 2000);
  };

  const handleCopyInvestigationSummary = () => {
    const lines = [
      `### [SOC FORENSIC DOSSIER] Indicator of Compromise (IOC)`,
      `**IP Address**: \`${ip}\``,
      `**Risk Score**: ${suspiciousData?.riskScore ?? 0}/100 (${suspiciousData?.riskLevel ?? 'LOW'})`,
      `**Status**: ${isBlocked ? 'BLOCKED / DROPPED' : isWhitelisted ? 'ALLOWLISTED' : 'ACTIVE / MONITORED'}`,
      `**Failed Logins**: ${suspiciousData?.failedLogins ?? 0} / Total Requests: ${suspiciousData?.totalRequests ?? ipLogs.length}`,
      `**Associated Users**: ${(suspiciousData?.associatedUsers ?? []).join(', ') || 'None detected'}`,
      `**Observed Time Range**: ${suspiciousData?.firstSeen ?? 'N/A'} -> ${suspiciousData?.lastSeen ?? 'N/A'}`,
      `**Triggered Indicators**:`,
      ...(suspiciousData?.reasons ?? ['Baseline activity']).map(r => `  - ${r}`),
      `**Root Cause Breakdown**:`,
      ...(suspiciousData?.failureReasons ?? []).map(f => `  - ${f.reason}: ${f.count} attempts`),
      `**Remediation Command**:`,
      `\`\`\`bash`,
      iptablesCommand,
      `aws wafv2 update-ip-set --name "SOC-Blocklist" --addresses "${ip}/32"`,
      `\`\`\``,
      `_Generated by SOC Incident Investigation Engine at ${new Date().toISOString()}_`
    ];

    navigator.clipboard.writeText(lines.join('\n'));
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2500);
  };

  const handleDownloadIPLogs = (format: 'json' | 'csv') => {
    let content = '';
    let mime = 'text/plain';
    let ext = format;

    if (format === 'json') {
      content = JSON.stringify({ ip, suspiciousData, logs: ipLogs }, null, 2);
      mime = 'application/json';
    } else {
      const headers = 'timestamp,event,ip,user,statusCode,failureReason,raw\n';
      const rows = ipLogs.map(l => 
        `"${l.timestamp}","${l.event}","${l.ip}","${l.user || ''}","${l.statusCode || ''}","${l.failureReason || ''}","${l.raw.replace(/"/g, '""')}"`
      ).join('\n');
      content = headers + rows;
      mime = 'text/csv';
    }

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `soc-ip-investigation-${ip.replace(/\./g, '-')}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const getRiskBadge = (level?: RiskLevel) => {
    switch (level) {
      case 'CRITICAL':
        return 'bg-red-500/20 text-red-400 border-red-500/40 font-bold';
      case 'HIGH':
        return 'bg-red-500/15 text-red-400 border-red-500/30 font-semibold';
      case 'MEDIUM':
        return 'bg-orange-500/15 text-orange-400 border-orange-500/30 font-medium';
      default:
        return 'bg-blue-500/15 text-blue-400 border-blue-500/30 font-medium';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="bg-[#0F172A] border border-[#334155] rounded-xl max-w-2xl w-full p-5 sm:p-6 shadow-2xl space-y-5 overflow-hidden font-sans">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-[#1E293B] pb-4">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-[#1E293B] rounded-lg border border-[#334155]">
              <ShieldAlert className="w-5 h-5 text-red-400" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-white font-mono">{ip}</h3>
                {suspiciousData && (
                  <span className={`px-2 py-0.5 rounded text-[10px] border font-mono ${getRiskBadge(suspiciousData.riskLevel)}`}>
                    {suspiciousData.riskLevel}
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-400">
                Deep Forensic Inspection & Remediation
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-2.5 py-1 rounded-lg bg-[#1E293B] hover:bg-slate-800 text-slate-300 hover:text-white border border-[#334155] text-xs font-mono flex items-center gap-1.5 transition-colors"
              title="Back to Previous View (ESC)"
            >
              <ArrowLeft className="w-3.5 h-3.5 text-blue-400" />
              <span>Back</span>
            </button>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-white p-1 rounded-lg transition-colors"
              aria-label="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Threat Summary Stats */}
        {suspiciousData ? (
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-[#111827] border border-[#334155] p-3 rounded-lg text-center font-mono">
              <span className="text-[10px] uppercase text-slate-500 font-bold block">Failed Logins</span>
              <span className="text-xl font-bold text-red-400">{suspiciousData.failedLogins}</span>
            </div>
            <div className="bg-[#111827] border border-[#334155] p-3 rounded-lg text-center font-mono">
              <span className="text-[10px] uppercase text-slate-500 font-bold block">Total Traffic</span>
              <span className="text-xl font-bold text-slate-200">{suspiciousData.totalRequests}</span>
            </div>
            <div className="bg-[#111827] border border-[#334155] p-3 rounded-lg text-center font-mono">
              <span className="text-[10px] uppercase text-slate-500 font-bold block">Risk Score</span>
              <span className="text-xl font-bold text-orange-400">{suspiciousData.riskScore}/100</span>
            </div>
          </div>
        ) : (
          <div className="bg-[#111827] border border-[#334155] p-3 rounded-lg text-xs text-slate-400">
            Host has not triggered suspicious activity thresholds. Total events logged: {ipLogs.length}
          </div>
        )}

        {/* Triggered Reasons */}
        {suspiciousData && suspiciousData.reasons.length > 0 && (
          <div className="space-y-1.5 font-mono text-xs">
            <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">
              Anomalous Indicators:
            </span>
            <div className="space-y-1">
              {suspiciousData.reasons.map((reason, idx) => (
                <div key={idx} className="flex items-center gap-2 text-red-400 bg-red-500/10 border border-red-500/20 px-2.5 py-1 rounded text-[11px]">
                  <AlertTriangle className="w-3.5 h-3.5 shrink-0" />
                  <span>{reason}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Failed Login Causes Breakdown */}
        {suspiciousData?.failureReasons && suspiciousData.failureReasons.length > 0 && (
          <div className="space-y-1.5 font-mono text-xs">
            <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1">
              <AlertCircle className="w-3 h-3 text-red-400" />
              <span>Failed Login Root Causes ({suspiciousData.failedLogins} total failures):</span>
            </span>
            <div className="flex flex-wrap gap-1.5">
              {suspiciousData.failureReasons.map((f, idx) => (
                <span 
                  key={idx} 
                  className="inline-flex items-center gap-1.5 px-2 py-1 rounded text-[10px] bg-red-950/50 border border-red-800/40 text-red-300 font-mono"
                >
                  <span className="font-semibold text-red-200">{f.reason}:</span>
                  <span className="text-white font-bold bg-red-900/60 px-1 py-0.2 rounded">{f.count}</span>
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Firewall Remediation Command */}
        <div className="bg-[#0B0E14] border border-[#334155] rounded-lg p-3 space-y-1.5">
          <div className="flex items-center justify-between text-[11px] text-slate-400 font-mono">
            <span>Recommended Firewall Drop Command:</span>
            <button
              onClick={handleCopyIptables}
              className="inline-flex items-center gap-1 text-[10px] text-blue-400 hover:text-blue-300 transition-colors"
            >
              {copiedIptables ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
              <span>{copiedIptables ? 'Copied' : 'Copy'}</span>
            </button>
          </div>
          <code className="block bg-black p-2 rounded text-xs text-green-400 font-mono select-all">
            {iptablesCommand}
          </code>
        </div>

        {/* Log Entries from this IP */}
        <div className="space-y-1.5 font-mono">
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">
            Correlated Log Entries ({ipLogs.length}):
          </span>
          <div className="max-h-36 overflow-y-auto bg-black border border-[#1E293B] rounded-lg p-2 space-y-1 text-[10px] text-slate-300">
            {ipLogs.map((log) => (
              <div key={log.id} className="flex items-center justify-between gap-2 p-1 border-b border-slate-900 last:border-0">
                <div className="flex items-center gap-2 truncate">
                  <span className="text-slate-500 shrink-0">{log.timestamp}</span>
                  <span className={log.event === 'LOGIN_FAILED' ? 'text-red-400 font-bold shrink-0' : 'text-green-400 shrink-0'}>
                    [{log.event}]
                  </span>
                  {log.failureReason && (
                    <span className="px-1.5 py-0.2 rounded text-[9px] bg-red-950/90 text-red-300 border border-red-800/60 font-mono shrink-0">
                      Reason: {log.failureReason}
                    </span>
                  )}
                  <span className="text-slate-300 truncate max-w-xs">{log.message || log.raw}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Actions Footer */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-2.5 pt-3 border-t border-[#1E293B]">
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={() => onToggleBlock(ip)}
              className={`px-3 py-1.5 rounded text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                isBlocked
                  ? 'bg-slate-800 text-slate-300 border border-slate-700'
                  : 'bg-red-600 hover:bg-red-500 text-white shadow-sm'
              }`}
            >
              <Ban className="w-3.5 h-3.5" />
              <span>{isBlocked ? 'Unblock Host' : 'Drop & Blacklist IP'}</span>
            </button>

            <button
              onClick={() => onToggleWhitelist(ip)}
              className={`px-3 py-1.5 rounded text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                isWhitelisted
                  ? 'bg-slate-800 text-slate-300 border border-slate-700'
                  : 'bg-[#1E293B] hover:bg-slate-800 text-slate-300 border border-[#334155]'
              }`}
            >
              <ShieldCheck className="w-3.5 h-3.5 text-green-400" />
              <span>{isWhitelisted ? 'Remove Whitelist' : 'Add to Allowlist'}</span>
            </button>

            {/* Copy Investigation Summary button */}
            <button
              onClick={handleCopyInvestigationSummary}
              className={`px-3 py-1.5 rounded text-xs font-semibold flex items-center gap-1.5 border transition-all ${
                copiedSummary
                  ? 'bg-emerald-950/80 border-emerald-500 text-emerald-300 shadow-sm'
                  : 'bg-blue-950/40 hover:bg-blue-900/60 border-blue-500/40 text-blue-300'
              }`}
              title="Copy formatted Markdown investigation briefing to clipboard"
            >
              {copiedSummary ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <FileText className="w-3.5 h-3.5 text-blue-400" />}
              <span>{copiedSummary ? 'Summary Copied!' : 'Copy Summary'}</span>
            </button>
          </div>

          <div className="flex items-center gap-2 self-end sm:self-auto">
            {/* Quick Export Dropdown */}
            <div className="flex items-center rounded border border-[#334155] bg-[#1E293B] overflow-hidden text-[11px] font-mono">
              <button
                onClick={() => handleDownloadIPLogs('csv')}
                className="px-2 py-1 text-slate-300 hover:text-white hover:bg-slate-800 border-r border-[#334155] flex items-center gap-1"
                title="Export this IP's logs as CSV"
              >
                <Download className="w-3 h-3 text-slate-400" />
                <span>CSV</span>
              </button>
              <button
                onClick={() => handleDownloadIPLogs('json')}
                className="px-2 py-1 text-slate-300 hover:text-white hover:bg-slate-800 flex items-center gap-1"
                title="Export this IP's logs as JSON"
              >
                <span>JSON</span>
              </button>
            </div>

            <button
              onClick={onClose}
              className="px-4 py-1.5 rounded bg-[#1E293B] hover:bg-slate-800 border border-[#334155] hover:border-slate-600 text-slate-200 text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-sm"
              title="Return to previous screen (ESC)"
            >
              <ArrowLeft className="w-3.5 h-3.5 text-blue-400" />
              <span>Back</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
